### ISSUE TITLE
Loading Stops untill LogView program is opened

### ISSUE THREAD

**Issue by troyBORG** [NepuShiro/ALogKrillIssue#2]
So in response to https://github.com/NepuShiro/ALogKrillIssue/issues/1 I tried closing the LogViewer program and now when I open the game it also stops.  But as soon as I open the LogViewer.exe it will continue loading and I can see the logs.

If its going to complain that it is already running, but then not work if its not running.  Should it just auto-open the program at the point its ready for it?

[DESKTOP-H0FLKOJ - 2024.6.11.74 - 2024-06-12 13_55_34.log](https://github.com/user-attachments/files/15809699/DESKTOP-H0FLKOJ.-.2024.6.11.74.-.2024-06-12.13_55_34.log)

**Comment by NepuShiro** [comment]
#1
These issues should be fixed in the latest release v1.0.5
If not, these can be re-opened
